version:"3"
service:
    apirest:
        container_name: apimadros
        restart: always
        build: .
        ports: 
            -"8080:3000"
        links: 
            - mongo
        mongo:
            container_name: madroñosdb
            image: mongo
            ports: 
                -"27018:27017"