version: '3'
services:
    apirest:
        container_name: apimadros
        restart: always
        build: .
        ports: 
            - "8080:3000"
        links: 
            - mongo
        volumes: 
            - .:/apimadro
    mongo:
        container_name: madronosdb
        image: mongo
        volumes:
            - ./mongo-volume:/data/db
        ports: 
             - "27017:27017"
        command:
            - mongorestore -d madroños /db/dbackup/dump/madroños
        logging: 
            driver: none